#!/usr/bin/env bash
# Writes an nginx include trusting Cloudflare's published ranges as the source
# of the real client IP (CF-Connecting-IP). Usage: cloudflare-ips.sh <output>
# On any failure the output file is left untouched and the script exits non-zero, so
# a deploy can fall back to the copy it already has.
set -euo pipefail

output="${1:?usage: cloudflare-ips.sh <output-file>}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    echo "# Cloudflare ranges, generated by deploy/cloudflare-ips.sh on $(date -u +%Y-%m-%d)."
    echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6. Do not edit by hand."
    for list in ips-v4 ips-v6; do
        curl -fsS --max-time 15 "https://www.cloudflare.com/${list}" | while read -r range; do
            [ -z "$range" ] && continue
            if ! [[ "$range" =~ ^[0-9a-fA-F:.]+/[0-9]{1,3}$ ]]; then
                echo "unexpected line from ${list}: ${range}" >&2
                exit 1
            fi
            echo "set_real_ip_from ${range};"
        done
    done
    echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"

if [ "$(grep -c '^set_real_ip_from' "$tmp")" -lt 10 ]; then
    echo "fewer than 10 Cloudflare ranges fetched - refusing to write ${output}" >&2
    exit 1
fi

chmod 644 "$tmp"
mv "$tmp" "$output"
trap - EXIT
