<?php

declare(strict_types=1);

namespace App\Modules\Quiz\Database\Seeders;

use App\Modules\Quiz\Domain\Entity\Attempt;
use App\Modules\Quiz\Domain\Repository\AttemptRepository;
use App\Modules\Quiz\Domain\ValueObject\AnswerId;
use App\Modules\Quiz\Domain\ValueObject\AttemptId;
use App\Modules\Quiz\Domain\ValueObject\SnapshotOption;
use App\Shared\Domain\Contract\QuestionBank;
use DateTimeImmutable;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Two finished quizzes for Carla in "Tabela Periódica", so the progress screens are
 * not empty in development: +60 then +40 → 100 points, Bronze, a few wrong answers.
 * Local/testing only; skips attempts that already exist, so re-running changes nothing.
 * Runs after ChemistryQuestionsSeeder (the bank) and DevelopmentAccountsSeeder (Carla).
 */
final class DevelopmentQuizSeeder extends Seeder
{
    /** Repeats DevelopmentAccountsSeeder::CARLA_ID: Quiz may not import Identity. */
    private const CARLA_ID = '0192f0a0-0000-7000-8000-000000000012';

    /** @var array<string, array{int, list<bool>}> attempt id => [days ago, answers in position order] */
    private const ATTEMPTS = [
        '0192f0a0-0000-7000-8000-000000000301' => [3, [true, true, true, true, true, true, true, true, false, false]],
        '0192f0a0-0000-7000-8000-000000000302' => [2, [true, true, true, true, true, false, false, false, true, true]],
    ];

    public function run(Application $app, QuestionBank $bank, AttemptRepository $attempts): void
    {
        if (! $app->environment('local', 'testing')) {
            return;
        }

        // Topic ids are generated by ChemistryTopicsSeeder: find the topic by its seeded name.
        $topicId = DB::table('topics')->where('name', 'Tabela Periódica')->value('id');
        $topic = is_string($topicId) ? $bank->topic($topicId) : null;

        if ($topic === null) {
            return;
        }

        $questions = $bank->activeQuestions($topic->id);

        foreach (self::ATTEMPTS as $id => [$daysAgo, $answers]) {
            $attemptId = new AttemptId($id);

            if ($attempts->findById($attemptId) !== null) {
                continue;
            }

            $startedAt = (new DateTimeImmutable("-$daysAgo days"))->setTime(10, 0);
            $attempt = Attempt::start($attemptId, self::CARLA_ID, $topic, $questions, new KeepOrder, $startedAt);
            $attempts->add($attempt);

            foreach ($attempt->questions() as $position => $question) {
                $correct = $answers[$position] ?? true;
                $option = $correct ? $question->correctOptionId() : $this->wrongOption($question->options(), $question->correctOptionId());
                $at = $startedAt->modify('+'.($position + 1).' minutes');
                $attempt->answer($question->id(), $option, AnswerId::random(), $at, $at);
                $attempts->saveAnswer($attempt);
            }
        }
    }

    /** @param list<SnapshotOption> $options */
    private function wrongOption(array $options, string $correct): string
    {
        foreach ($options as $option) {
            if ($option->id !== $correct) {
                return $option->id;
            }
        }

        return $correct;
    }
}
